<?php

namespace App\Http\Requests\role;

use Illuminate\Foundation\Http\FormRequest;

class StoreRequest extends FormRequest
{
    public function authorize()
    {
        return true;
    }

    public function rules()
    {
        return [
            'name' =>[
              'required',
            ],
        ];
    }

    public function messages()
    {
        return [
            'required' =>'Bắt buộc phải điền.'
        ];
        // TODO: Change the autogenerated stub
    }
}
